name: Commit Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
          npm install @commitlint/config-conventional@latest
      - name: Configure commitlint
        run: |
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
      - name: Validate new commits with commitlint
        if: github.event_name == 'push'
        run: |
          for sha in $(git rev-list ${{ github.event.before }}..${{ github.event.after }}); do
            git log -1 --pretty=%B $sha | npx commitlint --verbose
          done
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose